name: pre-commit

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write # required only when auto-commit is enabled
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup node dependencies
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v.6.3.0
        with:
          node-version-file: .nvmrc
      - uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@v15.7.1
        with:
          auto-commit: "true" # optionally commit automated fix changes back
